version: '3.1'

services:
  db:
    image: mariadb
    restart: always
    container_name: blog_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: blog_user
      MYSQL_PASSWORD: blog_pass
      MYSQL_DATABASE: blog
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysql" ,"-u", "blog_user", "-pblog_pass", "blog"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 5s

  php-fpm:
    image: nfqphuong/blog
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    expose:
      - 9000

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php-fpm
    ports:
    - "80:80"
